version : '3'

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  haproxy:
    image: haproxy:alpine
    platform: linux/x86_64
    container_name: haproxy
    restart: always
    depends_on:
      - instance1
      - instance2
      - instance3
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      - "80:80"

  instance1:
    build: ./service
    restart: always
    command: "5000"
    ports:
      - "5000:5000"
    expose:
      - 5000
    depends_on:
      - db

  instance2:
    build: ./service
    restart: always
    command: "5001"
    ports:
      - "5001:5001"
    expose:
      - 5001
    depends_on:
      - db

  instance3:
    build: ./service
    restart: always
    command: "5002"
    ports:
      - "5002:5002"
    expose:
      - 5002
    depends_on:
      - db